### ISSUE TITLE
Issue on generating the token

### ISSUE THREAD

**Issue by arpitb827** [mercadolibre/python-sdk#20]
Hi,

I tried to call authorize function for generating the token founding the error below.

Can you please help me on it.

Thanks
Arpit
>>> meli.authorize('TG-5a58c14fe4b0ff39be25d772-295295916', redirect_URI="https://bb6b4a5f.ngrok.io")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/melipy/core.py", line 49, in inner
  File "build/bdist.linux-x86_64/egg/melipy/core.py", line 89, in authorize
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.mercadolibre.com/oauth/token?code=TG-5a58c14fe4b0ff39be25d772-295295916&client_secret=Fn9k3FXuyPw921whwdtXJDAbGp2Ax4t9&grant_type=authorization_code&client_id=5961429306344932&redirect_uri=https%3A%2F%2Fbb6b4a5f.ngrok.io

**Comment by celm1990** [comment]
Hello,

I get same error, yesterday work fine, today get error, because???. Any update on api or python library???

**Comment by celm1990** [comment]
With Curl  get response:
![image](https://user-images.githubusercontent.com/7775116/37799454-ba34aa02-2ded-11e8-801a-c1f18f42c3c0.png)
With Python get error
![image](https://user-images.githubusercontent.com/7775116/37799505-ebd6dd46-2ded-11e8-9c58-223e33494412.png)

**Comment by celm1990** [comment]
Error is on Redirect URI, must be equals to configured on application
